#!/usr/bin/env bash
while [[ "$PROJECT_DIR" != */MobilePassThrough ]]; do PROJECT_DIR="$(readlink -f "$(dirname "${PROJECT_DIR:-0}")")"; done
source "$PROJECT_DIR/utils/helpers"
loadConfig

source "$DISTRO_UTILS_DIR/kernel-param-utils"

# This script doesn't do anything yet.