#!/usr/bin/env bash

GRUB_CFG_PATH=/etc/default/grub
VFIO_CFG_PATH=/etc/dracut.conf.d/vfio.conf

function addKernelParam() {
    if ! sudo cat "$GRUB_CFG_PATH" | grep "GRUB_CMDLINE_LINUX=" | grep --quiet "$1"; then
        sudo sed -i "s/^GRUB_CMDLINE_LINUX=\"/&$1 /" "$GRUB_CFG_PATH"
        echo "addKernelParam: Added \"$1\" to GRUB_CMDLINE_LINUX in $GRUB_CFG_PATH"
    else
        echo "addKernelParam: No action required. \"$1\" already exists in GRUB_CMDLINE_LINUX of $GRUB_CFG_PATH"
    fi
}
function removeKernelParam() {
    if sudo cat "$GRUB_CFG_PATH" | grep "GRUB_CMDLINE_LINUX=" | grep --quiet "$1"; then
        sudo sed -i "s/$1 //" "$GRUB_CFG_PATH"
        echo "removeKernelParam: Removed \"$1\" from GRUB_CMDLINE_LINUX in $GRUB_CFG_PATH"
    else
        echo "removeKernelParam: No action required. \"$1\" is not set in GRUB_CMDLINE_LINUX of $GRUB_CFG_PATH"
    fi
}
function applyKernelParamChanges() {
    sudo sh -c 'grub2-mkconfig > /etc/grub2-efi.cfg'
}

function setGrubTimeout() {
    sudo sed -i -r "s/^GRUB_TIMEOUT=[0-9]+/GRUB_TIMEOUT=$1 /" "$GRUB_CFG_PATH"
}

function addInitramfsDriver() {
    driver="$1"
    sudo touch "$VFIO_CFG_PATH"
    if ! sudo cat "$VFIO_CFG_PATH" | grep --quiet "add_driver+="; then
        echo 'add_driver+=" "' >> "$VFIO_CFG_PATH"
    fi 
    if ! sudo cat "$VFIO_CFG_PATH" | grep "add_driver+=" | grep --quiet -P "( |\")$driver( |\")"; then
        sudo sed -i "s/^add_driver+=\" \{0,1\}/&$driver /" "$VFIO_CFG_PATH"
        echo "addDriverToInitramfs: Added \"$driver\" to add_driver in $VFIO_CFG_PATH"
    else
        echo "addDriverToInitramfs: No action required. \"$driver\" already exists in add_driver in $VFIO_CFG_PATH"
    fi
}

function applyInitramfsChanges() {
    sudo dracut -f --kver `uname -r`
    #TODO: Find out if this needs to be executed again after every kernel update.
}

function runtimeKernelHasParam() {
    cmdline="$(cat /proc/cmdline)"
    [[ $cmdline =~ ^$1.* ]] || [[ $cmdline =~ .*$1$ ]] || [[ $cmdline = *" $1 "* ]]
}