#!/usr/bin/env bash

# This script has to be sourced and is not meant to be executed directly!
# How to use:
# while [[ "$PROJECT_DIR" != */MobilePassThrough ]]; do PROJECT_DIR="$(readlink -f "$(dirname "${PROJECT_DIR:-0}")")"; done
# source "$PROJECT_DIR/utils/helpers"

USER_SCRIPTS_DIR="${PROJECT_DIR}/scripts"
UTILS_DIR="${PROJECT_DIR}/utils"
DISTRO=$("${UTILS_DIR}/distro-info")
DISTRO_UTILS_DIR="${UTILS_DIR}/${DISTRO}"
THIRDPARTY_DIR="${PROJECT_DIR}/thirdparty"
ACPI_TABLES_DIR="${PROJECT_DIR}/acpi-tables"
LOG_BASE_DIR="${PROJECT_DIR}/logs"

shopt -s expand_aliases

function loadConfig() {
    # If user.conf doesn't exist use the default.conf
    if [ -f "${PROJECT_DIR}/user.conf" ]; then
        echo "> Loading config from ${PROJECT_DIR}/user.conf"
        source "${PROJECT_DIR}/user.conf"
    elif [ -f "${PROJECT_DIR}/default.conf" ]; then
        echo "> Warning: No user.conf found, falling back to default.conf"
        echo "> Loading config from ${PROJECT_DIR}/default.conf"
        source "${PROJECT_DIR}/default.conf"
    else
        echo "> Error: No user.conf or user.conf found!"
        exit
    fi
}