#!/usr/bin/env bash
while [[ "$PROJECT_DIR" != */MobilePassThrough ]]; do PROJECT_DIR="$(readlink -f "$(dirname "${PROJECT_DIR:-0}")")"; done
source "$PROJECT_DIR/scripts/utils/common/libs/helpers"
loadConfig

#####################################################################################################
# Simple script to install the packages containing the given executable names or file names
# Usage: `./apt --executables "curl git wget docker"`
# Usage: `./apt --files "/usr/include/{ree,ruby}/ruby.h /usr/share/virtio-win/virtio-win.iso"`
#####################################################################################################

alias getMissingExecutables="${COMMON_UTILS_TOOLS_DIR}/get-missing-executables"
alias getMissingFiles="${COMMON_UTILS_TOOLS_DIR}/get-missing-files"

SEARCH_MODE="$1"
WANTED_ITEMS="$2"

function installPackages() {
    SEARCH_MODE="$1"
    WANTED_ITEMS="$2"
    
    sudo apt-get update > /dev/null
    if ! command -v apt-file &> /dev/null; then
        apt-get install -y apt-file
    fi
    PACKAGES_TO_INSTALL=""
    for CURRENT_ITEM in $WANTED_ITEMS; do
        if [ "$SEARCH_MODE" = "--executables" ]; then
            PACKAGE_TO_INSTALL="$(sudo apt-file search {/bin,/sbin,/usr/bin/,/usr/sbin}/$CURRENT_ITEM | head -1 | cut -d':' -f1)"
        elif [ "$SEARCH_MODE" = "--files" ]; then
            PACKAGE_TO_INSTALL="$(sudo apt-file search $CURRENT_ITEM | head -1 | cut -d':' -f1))"
        fi
        if [ "$?" = "0" ] && [ "$PACKAGE_TO_INSTALL" != "" ]; then
            PACKAGES_TO_INSTALL+=" $PACKAGE_TO_INSTALL"
        else
            STILL_MISSING_ITEMS+=" $CURRENT_ITEM"
        fi
    done
    if [ "$PACKAGES_TO_INSTALL" != "" ]; then
        sudo apt-get install -y $PACKAGES_TO_INSTALL
    fi
}

if [ "$SEARCH_MODE" = "--executables" ]; then
    MISSING_EXECUTABLES="$(getMissingExecutables "$WANTED_ITEMS")"
    installPackages "$SEARCH_MODE" "$MISSING_EXECUTABLES"
    echo "Still missing: $(getMissingExecutables "$WANTED_ITEMS")"
elif [ "$SEARCH_MODE" = "--files" ]; then
    MISSING_FILES="$(getMissingFiles "$WANTED_ITEMS")"
    installPackages "$SEARCH_MODE" "$MISSING_FILES"
    echo "Still missing: $(getMissingFiles "$WANTED_ITEMS")"
fi