#!/usr/bin/env bash

SCRIPT_DIR=$(cd "$(dirname "$0")"; pwd)
PROJECT_DIR="${SCRIPT_DIR}/../../.."
UTILS_DIR="${PROJECT_DIR}/utils"
DISTRO=$("${UTILS_DIR}/distro-info")
DISTRO_UTILS_DIR="${UTILS_DIR}/${DISTRO}"
VM_FILES_DIR="${PROJECT_DIR}/vm-files"

VM_DISK_SIZE="${VM_DISK_SIZE:=20G}"

echo "Creating a virtual disk for the VM..."
qemu-img create -f raw "${VM_FILES_DIR}/WindowsVM.img" "${VM_DISK_SIZE}"

echo "Generating a MAC address for the VM..."
printf '52:54:BE:EF:%02X:%02X\n' $((RANDOM%256)) $((RANDOM%256)) > "${VM_FILES_DIR}/MAC_ADDRESS.txt"

echo "Creating a copy of OVMF_VARS.fd (containing the executable firmware code and but the non-volatile variable store) for the VM..."
sudo cp /usr/share/OVMF/OVMF_VARS.fd "${VM_FILES_DIR}/WIN_VARS.fd"

echo "Creating ${VM_FILES_DIR}/vbios-roms for the VM..."
mkdir -p "${VM_FILES_DIR}/vbios-roms"

echo "Creating ${VM_FILES_DIR}/vmshare for the VM..."
mkdir -p "${VM_FILES_DIR}/vmshare"
