#!/usr/bin/env bash
while [[ "$PROJECT_DIR" != */MobilePassThrough ]]; do PROJECT_DIR="$(readlink -f "$(dirname "${PROJECT_DIR:-0}")")"; done
source "$PROJECT_DIR/scripts/utils/common/libs/helpers"

echo "Install third party repositories"
sudo add-apt-repository ppa:bumblebee/testing -y

echo "Install Bumblebee"
sudo apt install bumblebee bumblebee-nvidia -y

echo "Make Bumblebee available to the current user"
sudo gpasswd -a $(whoami) bumblebee

echo "Enable Bumblebee autostart"
sudo systemctl enable bumblebeed

echo "Block nvidia-fallback service"
sudo systemctl mask nvidia-fallback

echo "Start Bumblebee"
sudo systemctl start bumblebeed
