#!/usr/bin/env bash
while [[ "$PROJECT_DIR" != */MobilePassThrough ]]; do PROJECT_DIR="$(readlink -f "$(dirname "${PROJECT_DIR:-0}")")"; done
source "$PROJECT_DIR/scripts/utils/common/libs/helpers"
loadConfig

source "$DISTRO_UTILS_DIR/kernel-param-utils"

#TODO: verify if that actually works:
echo "Allow using external monitor for notebooks that have the port wired to the dGPU directly"
sudo apt install -y intel-gpu-tools
sudo intel-virtual-output
#example usage: xrandr –output eDP1 –mode 1920×1080 –output HDMI1 –mode 1920×1080 –right-of eDP1
