#!/usr/bin/env bash
while [[ "$PROJECT_DIR" != */MobilePassThrough ]]; do PROJECT_DIR="$(readlink -f "$(dirname "${PROJECT_DIR:-0}")")"; done
source "$PROJECT_DIR/scripts/utils/common/libs/helpers"

#####################################################################################################
# This script compiles the asm source code for the SSDT table that contains a fake battery for the VM.
# Usage: `./build-fake-battery-ssdt`
#####################################################################################################

iasl "${ACPI_TABLES_DIR}/fake-battery.asl" # creates fake-battery.aml