#!/usr/bin/env bash
while [[ "$PROJECT_DIR" != */MobilePassThrough ]]; do PROJECT_DIR="$(readlink -f "$(dirname "${PROJECT_DIR:-0}")")"; done
source "$PROJECT_DIR/scripts/utils/common/libs/helpers"

#####################################################################################################
# This script compiles the asm source code for the SSDT table that contains a fake battery for the VM.
# Usage: `./build-fake-battery-ssdt`
#####################################################################################################

VIRTIO_WIN_VERSION="0.1.196"
if [ ! -f "${THIRDPARTY_DIR}/virtio-win.iso" ]; then
    wget "https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-${VIRTIO_WIN_VERSION}-1/virtio-win.iso" -O "${THIRDPARTY_DIR}/virtio-win.iso"
fi