#!/usr/bin/env bash
while [[ "$PROJECT_DIR" != */MobilePassThrough ]]; do PROJECT_DIR="$(readlink -f "$(dirname "${PROJECT_DIR:-0}")")"; done

COMMAND="$1"
COMMAND_TO_EXECUTE="$2"

if [ "$COMMAND" = "run-with-command" ]; then
    gnome-terminal -- bash -c "$COMMAND_TO_EXECUTE"
fi
