#!/usr/bin/env bash
while [[ "$PROJECT_DIR" != */MobilePassThrough ]]; do PROJECT_DIR="$(readlink -f "$(dirname "${PROJECT_DIR:-0}")")"; done
source "$PROJECT_DIR/scripts/utils/common/libs/helpers"

COMMAND="$1"
COMMAND_TO_EXECUTE="$2"

if [ "$COMMAND" = "run-with-command" ]; then
    x-terminal-emulator -e "$COMMAND_TO_EXECUTE"
fi
