#!/usr/bin/env bash
while [[ "$PROJECT_DIR" != */MobilePassThrough ]]; do PROJECT_DIR="$(readlink -f "$(dirname "${PROJECT_DIR:-0}")")"; done
source "$PROJECT_DIR/utils/helpers"
loadConfig

mkdir -p "${PROJECT_DIR}/thirdparty"
cd "${PROJECT_DIR}/thirdparty"

sudo dnf install -y binutils-devel cmake texlive-gnu-freefont fontconfig-devel SDL2-devel SDL2_ttf-devel spice-protocol libX11-devel nettle-devel wayland-protocols-devel gcc libXScrnSaver-devel libXfixes-devel libXi-devel wayland-devel mingw64-gcc-c++ mingw32-nsis

LOOKING_GLASS_VERSION="B4"

# Build the (Linux) client application
git clone --single-branch --branch "${LOOKING_GLASS_VERSION}" --depth 1 --recursive https://github.com/gnif/LookingGlass.git
mkdir  LookingGlass/client/build
cd LookingGlass/client/build
cmake ../
make

sudo bash -c "echo '#Type Path Mode UID GID Age Argument' > /etc/tmpfiles.d/10-looking-glass.conf"
sudo bash -c "echo 'f /dev/shm/looking-glass 0660 $(logname) kvm - ' >> /etc/tmpfiles.d/10-looking-glass.conf"

# Build the (Windows) host application
cd "${PROJECT_DIR}/thirdparty"
wget https://developer.nvidia.com/capture_sdk/downloads/v8.0.4/linux -O ./nvidea_capture_api.tgz
rm -rf ./Capture_Linux_v8.0.4
tar -xvzf ./nvidea_capture_api.tgz 
rm ./nvidea_capture_api.tgz
rm -rf ./LookingGlass/Capture_Linux_v8.0.4
mv ./Capture_Linux_v8.0.4 ./LookingGlass/
cd LookingGlass
cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_TOOLCHAIN_FILE=./host/toolchain-mingw64.cmake -DNVFBC_SDK='./Capture_Linux_v8.0.4' -DUSE_NVFBC=1 ./host
make

#wget "https://ci.appveyor.com/api/projects/rainers/visuald/artifacts/cv2pdb.exe?job=Environment%3A%20os%3DVisual%20Studio%202015%2C%20VS%3D14%2C%20APPVEYOR_BUILD_WORKER_IMAGE%3DVisual%20Studio%202015" -O "cv2pdb.exe"
#wine './cv2pdb.exe' './looking-glass-host.exe'
makensis './platform/Windows/installer.nsi'
