#!/usr/bin/env bash
while [[ "$PROJECT_DIR" != */MobilePassThrough ]]; do PROJECT_DIR="$(readlink -f "$(dirname "${PROJECT_DIR:-0}")")"; done
source "$PROJECT_DIR/scripts/utils/common/libs/helpers"

COMMAND="$1"

SERVICE_NAME="$2"
if [ "$COMMAND" = "create-autostart-service" ]; then
    COMMAND_TO_RUN="$2"
    EXEC_START="'$GUI_TERMINAL' run-with-command '$COMMAND_TO_RUN'"
    
    sudo echo "[Unit]
Description=${SERVICE_NAME}
After=multi-user.target network.target

[Service]
User=$(logname)
Group=$(id -gn $(logname))
Type=simple
Environment=DISPLAY=:0
WorkingDirectory=${PROJECT_DIR}
ExecStart=${EXEC_START}
Restart=never

[Install]
WantedBy=multi-user.target" > /etc/systemd/system/${SERVICE_NAME}.service

    sudo systemctl daemon-reload
    sudo systemctl enable ${SERVICE_NAME}.service
elif [ "$COMMAND" = "remove-autostart-service" ]; then
    sudo systemctl disable ${SERVICE_NAME}.service &> /dev/null
elif [ "$COMMAND" = "start" ]; then
    sudo systemctl start ${SERVICE_NAME}.service &> /dev/null
elif [ "$COMMAND" = "stop" ]; then
    sudo systemctl stop ${SERVICE_NAME}.service &> /dev/null
elif [ "$COMMAND" = "restart" ]; then
    sudo systemctl restart ${SERVICE_NAME}.service &> /dev/null
fi
