#!/usr/bin/env bash

#####################################################################################################
# Simple script to install the package containing the given executable name
# Usage: `./install-packages --executables "curl git wget docker"`
# Usage: `./install-packages --files "/usr/include/{ree,ruby}/ruby.h /usr/share/virtio-win/virtio-win.iso"`
#####################################################################################################

SEARCH_MODE="$1"
WANTED_ITEMS="$2"

function getMissingExecutables() {
    EXECUTABLES_MISSING=""
    for CURRENT_EXECUTABLE in $1; do
        if ! command -v $CURRENT_EXECUTABLE &> /dev/null; then
            EXECUTABLES_MISSING+=" $CURRENT_EXECUTABLE"
        fi
    done
    echo "$EXECUTABLES_MISSING"
}

function getMissingFiles() {
    FILES_MISSING=""
    for CURRENT_FILE in $1; do
        if [ ! -f "$CURRENT_FILE" ]; then
            FILES_MISSING+=" $CURRENT_FILE"
        fi
    done
    echo "$FILES_MISSING"
}

function installPackages() {
    SEARCH_MODE="$1"
    WANTED_ITEMS="$2"
    
    if command -v dnf &> /dev/null; then # If package manager is dnf
        sudo dnf check-update
        PACKAGES_TO_INSTALL=""
        for CURRENT_ITEM in $WANTED_ITEMS; do
            if [ "$SEARCH_MODE" = "--executables" ]; then
                PACKAGE_TO_INSTALL="$(sudo dnf whatprovides "$CURRENT_ITEM" 2> /dev/null | grep ' : ' | head -2 | tail -1 | cut -d'.' -f1 | rev | cut -d'-' -f 2- | rev)"
            elif [ "$SEARCH_MODE" = "--files" ]; then
                PACKAGE_TO_INSTALL="$(sudo dnf provides "$CURRENT_ITEM" 2> /dev/null | grep ' : ' | head -2 | tail -1 | cut -d'.' -f1 | rev | cut -d'-' -f 2- | rev)"
            fi
            if [ "$?" = "0" ] && [ "$PACKAGE_TO_INSTALL" != "" ]; then
                PACKAGES_TO_INSTALL+=" $PACKAGE_TO_INSTALL"
            else
                STILL_MISSING_ITEMS+=" $CURRENT_ITEM"
            fi
        done
        if [ "$PACKAGES_TO_INSTALL" != "" ]; then
            sudo dnf install -y $PACKAGES_TO_INSTALL
        fi
    elif command -v apt-get &> /dev/null; then # If package manager is apt
        sudo apt-get update
        if ! command -v apt-file &> /dev/null; then
            apt-get install -y apt-file
        fi
        PACKAGES_TO_INSTALL=""
        for CURRENT_ITEM in $WANTED_ITEMS; do
            if [ "$SEARCH_MODE" = "--executables" ]; then
                PACKAGE_TO_INSTALL="$(sudo apt-file search "/usr/bin/$CURRENT_ITEM" | head -1 | cut -d':' -f1)"
            elif [ "$SEARCH_MODE" = "--files" ]; then
                PACKAGE_TO_INSTALL="$(sudo apt-file search "$CURRENT_ITEM" | head -1 | cut -d':' -f1))"
            fi
            if [ "$?" = "0" ] && [ "$PACKAGE_TO_INSTALL" != "" ]; then
                PACKAGES_TO_INSTALL+=" $PACKAGE_TO_INSTALL"
            else
                STILL_MISSING_ITEMS+=" $CURRENT_ITEM"
            fi
        done
        if [ "$PACKAGES_TO_INSTALL" != "" ]; then
            sudo apt-get install -y $PACKAGES_TO_INSTALL
        fi
    fi

    #echo "Couldn't find packages for: $STILL_MISSING_ITEMS"
}

if [ "$SEARCH_MODE" = "--executables" ]; then
    MISSING_EXECUTABLES="$(getMissingExecutables "$WANTED_ITEMS")"
    installPackages "$SEARCH_MODE" "$MISSING_EXECUTABLES"
    echo "Still missing: $(getMissingExecutables "$WANTED_ITEMS")"
elif [ "$SEARCH_MODE" = "--files" ]; then
    MISSING_FILES="$(getMissingFiles "$WANTED_ITEMS")"
    installPackages "$SEARCH_MODE" "$MISSING_FILES"
    echo "Still missing: $(getMissingFiles "$WANTED_ITEMS")"
fi