#!/usr/bin/env bash

function runtimeKernelHasParam() {
    cmdline="$(cat /proc/cmdline)"
    [[ $cmdline =~ ^$1.* ]] || [[ $cmdline =~ .*$1$ ]] || [[ $cmdline = *" $1 "* ]]
}

function runtimeKernelHasParams() {
    for param in $1; do
        runtimeKernelHasParam "$param"
    done
}

runtimeKernelHasParams "$1"