#!/usr/bin/env bash

SCRIPT_DIR=$(cd "$(dirname "$0")"; pwd)
PROJECT_DIR="${SCRIPT_DIR}/../../.."
UTILS_DIR="${PROJECT_DIR}/utils"
DISTRO=$("${UTILS_DIR}/distro-info")
DISTRO_UTILS_DIR="${UTILS_DIR}/${DISTRO}"
VM_FILES_DIR="${PROJECT_DIR}/vm-files"


sudo dnf install -y git SDL2-devel SDL2_ttf-devel openssl-devel spice-protocol fontconfig-devel libX11-devel gnu-free-mono-fonts ivshmem-tools libgle-devel.x86_64 cmake nettle-devel libconfig-devel libwayland-egl-devel

sudo dnf groupinstall -y "Development Tools" "Development Libraries"

git clone https://github.com/gnif/LookingGlass.git
git checkout tags/a12
mkdir  LookingGlass/client/build
cd LookingGlass/client/build
cmake ../
make
cd LookingGlass/client
make

sudo usermod -aG qemu $LOGNAME

sudo touch /dev/shm/looking-glass
sudo chown $LOGNAME:kvm /dev/shm/looking-glass
sudo chmod 660 /dev/shm/looking-glass
