#!/usr/bin/env bash

echo "Updating software..."
sudo dnf update -y
echo "Installing some useful tools..."
sudo dnf install -y wget curl vim screen git crudini lshw msr-tools sysfsutils tunctl remmina samba spice-gtk-tools genisoimage uuid acpica-tools docker
echo "Installing virtualization software..."
sudo dnf install -y qemu #@virtualization

echo "Installing the Windows VirtIO Repository..."
sudo wget https://fedorapeople.org/groups/virt/virtio-win/virtio-win.repo -O /etc/yum.repos.d/virtio-win.repo
echo "Installing virtio-win..."
sudo dnf install virtio-win -y
echo "Upgrading to latest virtio-win..."
sudo dnf --enablerepo=virtio-win-latest upgrade virtio-win -y
echo "Installing virt-viewer so you can connect to the VM for the windows installation"
sudo dnf install -y virt-viewer
# /usr/share/virtio-win/virtio-win.iso
