#!/usr/bin/env bash

SCRIPT_DIR=$(cd "$(dirname "$0")"; pwd)
PROJECT_DIR="${SCRIPT_DIR}/.."
UTILS_DIR="${PROJECT_DIR}/utils"
DISTRO=$("${UTILS_DIR}/distro-info")
DISTRO_UTILS_DIR="${UTILS_DIR}/${DISTRO}"

ACPI_TABLES_DIR="$(readlink -f "${PROJECT_DIR}/acpi-tables")"

# This script compiles the asm source code for the SSDT table that contains a fake battery for the VM.

iasl "${ACPI_TABLES_DIR}/fake-battery.asl" # creates fake-battery.aml