#!/usr/bin/env bash

shopt -s nullglob
for d in /sys/kernel/iommu_groups/*/devices/*; do
    n=${d#*/iommu_groups/*}; n=${n%%/*}
    printf 'IOMMU Group %s ' "$n"
    if [[ $d =~ "." ]]; then
        lspci -nns "${d##*/}"
    else
        printf "$(readlink -f "${d}" | cut -d'/' -f5- | cut -d':' -f2-) Virtual GPU of: "
        lspci -nns "$(basename "$(dirname "$(readlink -f "${d}")")")" | cut -d' ' -f2-
    fi
done;
