#!/usr/bin/env bash

# This script builds a Docker image that allows us to patch OVMF_CODE.fd and OVMF_VARS.fd with your vBIOS ROM.
# This helps circumvent Nvidia's Error 43 in some cases.

sudo service docker start
git clone https://github.com/T-vK/ovmf-with-vbios-patch.git
cd ovmf-with-vbios-patch
sudo docker build -t ovmf-vbios-patch .