#!/usr/bin/env bash

SCRIPT_DIR=$(cd "$(dirname "$0")"; pwd)
PROJECT_DIR="${SCRIPT_DIR}/.."
UTILS_DIR="${PROJECT_DIR}/utils"
DISTRO=$("${UTILS_DIR}/distro-info")
DISTRO_UTILS_DIR="${UTILS_DIR}/${DISTRO}"

mkdir -p "${PROJECT_DIR}/thirdparty"
cd "${PROJECT_DIR}/thirdparty"

SCHILY_VERSION="2021-06-07"
SCHILY_ARCHIVE="schily-${SCHILY_VERSION}.tar.bz2"
SCHILY_DIR="${PROJECT_DIR}/thirdparty/schily-tools"
sudo rm -rf "${SCHILY_DIR}"
wget "https://altushost-swe.dl.sourceforge.net/project/schilytools/${SCHILY_ARCHIVE}" -O "${SCHILY_ARCHIVE}"
tar -xf "${SCHILY_ARCHIVE}"
rm "${SCHILY_ARCHIVE}"
mv "schily-${SCHILY_VERSION}" "${SCHILY_DIR}"
cd "${SCHILY_DIR}"
./Gmake.linux