#!/usr/bin/env bash

GRUB_CFG_PATH=/etc/default/grub

COMMAND="$1" # Supported comamnds: add, remove, apply
PARAM="$2"

function addKernelParam() {
    if ! sudo cat "$GRUB_CFG_PATH" | grep "GRUB_CMDLINE_LINUX=" | grep --quiet "$1"; then
        sudo sed -i "s/^GRUB_CMDLINE_LINUX=\"/&$1 /" "$GRUB_CFG_PATH"
        echo "addKernelParam: Added \"$1\" to GRUB_CMDLINE_LINUX in $GRUB_CFG_PATH"
    else
        echo "addKernelParam: No action required. \"$1\" already exists in GRUB_CMDLINE_LINUX of $GRUB_CFG_PATH"
    fi
}
function addKernelParams() {
    for param in $1; do
        addKernelParam "$param"
    fi
}
function removeKernelParam() {
    if sudo cat "$GRUB_CFG_PATH" | grep "GRUB_CMDLINE_LINUX=" | grep --quiet "$1"; then
        sudo sed -i "s/$1 //" "$GRUB_CFG_PATH"
        echo "removeKernelParam: Removed \"$1\" from GRUB_CMDLINE_LINUX in $GRUB_CFG_PATH"
    else
        echo "removeKernelParam: No action required. \"$1\" is not set in GRUB_CMDLINE_LINUX of $GRUB_CFG_PATH"
    fi
}
function removeKernelParams() {
    for param in $1; do
        removeKernelParam "$param"
    fi
}

function applyKernelParamChanges() {
    sudo sh -c 'grub2-mkconfig > /etc/grub2-efi.cfg'
}

if [ "$COMMAND" = "add" ]; then
    addKernelParams "$PARAM"
elif [ "$COMMAND" = "remove" ]; then
    removeKernelParams "$PARAM"
elif [ "$COMMAND" = "apply" ]; then
    applyKernelParamChanges
fi