#!/usr/bin/env bash
while [[ "$PROJECT_DIR" != */MobilePassThrough ]]; do PROJECT_DIR="$(readlink -f "$(dirname "${PROJECT_DIR:-0}")")"; done
source "$PROJECT_DIR/utils/helpers"

# This script builds a Docker image that allows us to patch OVMF_CODE.fd and OVMF_VARS.fd with your vBIOS ROM.
# This helps circumvent Nvidia's Error 43 in some cases.

mkdir -p "${PROJECT_DIR}/thirdparty"
cd "${PROJECT_DIR}/thirdparty"

sudo service docker start
git clone https://github.com/T-vK/ovmf-with-vbios-patch.git
cd ovmf-with-vbios-patch
sudo docker build -t ovmf-vbios-patch .