#!/usr/bin/env bash

echo "Updating software..."
sudo apt upgrade -y
echo "Installing some useful tools..."
sudo apt install -y wget curl vim screen git crudini lshw msr-tools sysfsutils uml-utilities remmina samba spice-client-gtk genisoimage uuid acpica-tools
sudo snap install docker
echo "Installing virtualization software..."
sudo apt install qemu-kvm qemu-utils qemu-efi ovmf qemu -y

#echo "Installing the Windows VirtIO Repository..."
#sudo wget https://fedorapeople.org/groups/virt/virtio-win/virtio-win.repo -O /etc/yum.repos.d/virtio-win.repo
echo "Installing virtio-modules"
sudo apt install virtio-modules -y
#echo "Upgrading to latest virtio-win..."
#sudo dnf --enablerepo=virtio-win-latest upgrade virtio-win -y
echo "Installing virt-viewer so you can connect to the VM for the windows installation"
sudo apt install -y virt-viewer
# /usr/share/virtio-win/virtio-win.iso
