#!/usr/bin/env bash

SCRIPT_DIR=$(cd "$(dirname "$0")"; pwd)
PROJECT_DIR="${SCRIPT_DIR}/../../.."
UTILS_DIR="${PROJECT_DIR}/utils"
DISTRO=$("${UTILS_DIR}/distro-info")
DISTRO_UTILS_DIR="${UTILS_DIR}/${DISTRO}"
VM_FILES_DIR="${PROJECT_DIR}/vm-files"

source "$DISTRO_UTILS_DIR/kernel-param-utils"

echo "Disable Nouveau drivers"
addKernelParam "nouveau.modeset=0"
#sudo grep -qxsF 'blacklist nouveau' "/etc/modprobe.d/blacklist.conf" || echo "blacklist nouveau" | sudo tee -a "/etc/modprobe.d/blacklist.conf" > /dev/null
#sudo grep -qxsF 'exclude=xorg-x11*' "/etc/dnf/dnf.conf" || echo "exclude=xorg-x11*" | sudo tee -a "/etc/dnf/dnf.conf" > /dev/null
#sudo dnf remove xorg-x11-drv-nouveau -y

echo "Install third party repositories"
sudo add-apt-repository ppa:graphics-drivers/ppa -y

echo "Auto-install NVIDIA Drivers with ubuntu-drivers"
sudo ubuntu-drivers install -y

echo "Add Bumblebee repository"
sudo add-apt-repository ppa:bumblebee/testing -y


echo "Install Bumblebee"
sudo apt install bumblebee bumblebee-nvidia primus -y

echo "Make Bumblebee available to the current user"
sudo usermod -aG bumblebee $(whoami)

echo "Enable Bumblebee autostart"
sudo systemctl enable bumblebeed

echo "Block nvidia-fallback service"
sudo systemctl mask nvidia-fallback

echo "Start Bumblebee"
sudo systemctl start bumblebeed
