#!/usr/bin/env bash

SCRIPT_DIR=$(cd "$(dirname "$0")"; pwd)
PROJECT_DIR="${SCRIPT_DIR}/../../.."
UTILS_DIR="${PROJECT_DIR}/utils"
DISTRO=$("${UTILS_DIR}/distro-info")
DISTRO_UTILS_DIR="${UTILS_DIR}/${DISTRO}"
VM_FILES_DIR="${PROJECT_DIR}/vm-files"
="${PROJECT_DIR}/vm-files"
_DIR="${PROJECT_DIR}/vm-files"

mkdir -p "${PROJECT_DIR}/thirdparty"
cd "${PROJECT_DIR}/thirdparty"

rm -rf VBiosFinder
git clone https://github.com/coderobe/VBiosFinder.git
cd VBiosFinder

sudo apt install ruby ruby-rubygems ruby-bundler ruby-dev p7zip innoextract upx -y


wget https://github.com/LongSoft/UEFITool/releases/download/A58/UEFIExtract_NE_A58_linux_x86_64.zip -O ./UEFIExtract.zip
unzip ./UEFIExtract.zip -d ./3rdparty/
rm -f ./UEFIExtract.zip

git clone https://github.com/awilliam/rom-parser.git
cd rom-parser

bundle install --path=vendor/bundle
gem install bundler:1.17.3

make
mv ./rom-fixer ../3rdparty/
mv ./rom-parser ../3rdparty/
cd ..

bundle install --path=vendor/bundle

