#!/usr/bin/env bash

git clone https://github.com/coderobe/VBiosFinder.git
cd VBiosFinder

sudo apt install ruby ruby-rubygems ruby-bundler ruby-dev p7zip innoextract upx -y

wget https://github.com/LongSoft/UEFITool/releases/download/A58/UEFIExtract_NE_A58_linux_x86_64.zip -O ./UEFIExtract.zip
unzip ./UEFIExtract.zip -d ./3rdparty/

git clone https://github.com/awilliam/rom-parser.git
cd rom-parser

bundle install --path=vendor/bundle
gem install bundler:1.17.3

make
cp ./rom-fixer ../3rdparty/
cp ./rom-parser ../3rdparty/
cd ..

bundle install --path=vendor/bundle
