#!/usr/bin/env bash
while [[ "$PROJECT_DIR" != */MobilePassThrough ]]; do PROJECT_DIR="$(readlink -f "$(dirname "${PROJECT_DIR:-0}")")"; done
source "$PROJECT_DIR/scripts/utils/common/libs/helpers"

echo "Install third party repositories"
sudo dnf install fedora-workstation-repositories -y

echo "Enable the Bumblebee repository"
sudo dnf copr enable chenxiaolong/bumblebee -y

echo "Install Bumblebee"
sudo dnf install akmod-bbswitch bumblebee primus -y

echo "Make Bumblebee avialable to the current user"
sudo gpasswd -a $(who -m | awk '{print $1;}') bumblebee

echo "Enable Bumblebee autostart"
sudo systemctl enable bumblebeed

echo "Block nvidia-fallback service"
sudo systemctl mask nvidia-fallback

echo "Start Bumblebee"
sudo systemctl start bumblebeed