#!/usr/bin/env bash
while [[ "$PROJECT_DIR" != */MobilePassThrough ]]; do PROJECT_DIR="$(readlink -f "$(dirname "${PROJECT_DIR:-0}")")"; done
source "$PROJECT_DIR/scripts/utils/common/libs/helpers"
loadConfig

source "$DISTRO_UTILS_DIR/kernel-param-utils"

#TODO: verify if that actually works:
#echo "Allow using external monitor for notebooks that have the port wired to the dGPU directly"
if ! command -v intel-virtual-output &> /dev/null; then
    sudo dnf install -y intel-gpu-tools
fi
#sudo intel-virtual-output # TODO: Check if this should be added to the start-vm.sh
#example usage: xrandr –output eDP1 –mode 1920×1080 –output HDMI1 –mode 1920×1080 –right-of eDP1
